version: '2'

services:
    postgres:
        image: postgres:9.5.6-alpine
        restart: unless-stopped
        expose:
            - "5432"
        volumes:
            - ./data/postgres:/var/lib/postgresql/data

    pgadmin:
        build: ./pgadmin
        restart: unless-stopped
        environment:
            - SERVER_MODE=True
            - PGADMIN_SETUP_EMAIL=robinm8@rpi.edu
            - PGADMIN_SETUP_PASSWORD=robinm8
        expose:
            - "80"
        links:
            - postgres
        volumes:
            - ./pgadmin/pgadmin4/config_local.py:/usr/local/lib/python2.7/site-packages/pgadmin4/config_local.py
              pgadmin/pgadmin4/pgadmin/redirects
            - ./pgadmin/pgadmin4/pgadmin/redirects/__init__.py:/usr/local/lib/python2.7/site-packages/pgadmin4/pgadmin/redirects/__init__.py
            - ./pgadmin/data:/data

    nginx:
        build: ./nginx
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        links:
            - web
            - pgadmin
        volumes:
            - .:/usr/src/app/
            - ./nginx/:/etc/nginx/

    redis:
        image: redis
        restart: unless-stopped
        expose:
            - "6379"

    web:
        build: .
        restart: unless-stopped
        environment:
            - RAILS_ENV=${RAILS_ENV}
            - SECRET_KEY_BASE=${SECRET_KEY_BASE}
            - SECRET_TOKEN=${SECRET_TOKEN}
            - WEB_CONCURRENCY=${WEB_CONCURRENCY}
            - MAX_THREADS=${MAX_THREADS}
        volumes:
            - .:/usr/src/app/
            - ./nginx/:/etc/puma/
        depends_on:
            - postgres
        command: bundle exec puma -C config/puma.rb
        expose:
            - "3000"

    worker:
        build: .
        restart: unless-stopped
        environment:
            - RAILS_ENV=${RAILS_ENV}
        volumes:
            - .:/usr/src/app/
        depends_on:
            - postgres
        command: bundle exec crono
